project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!certificate*"
  resources:
    - "files/"
  preview:
    port: 4321
    browser: true

execute:
  # Re-render only when source changes
  freeze: auto

description-meta: "Katherine Siegel"

website:
  title: "Katherine Siegel"
  site-url: "https://github.com/katherinesiegel/website"
  repo-url: https://github.com/katherinesiegel/website
  description: "Katherine Siegel"
  # favicon: /files/icon.png 
  twitter-card: 
    creator: "@kjohannetsiegel"
  cookie-consent: true    
  search: true
  sidebar:
    background: "#5A8B92"
    pinned: true
    align: center 
    tools:
      - icon: github
        href: https://github.com/katherinesiegel/website
    style: docked
    contents:
      - text: "About"
        href: "index.qmd"
      - text: "Research"
        href: "research.qmd"
      - text: "Publications"
        href: "publications.qmd"
      - text: "Teaching"
        href: "teaching.qmd"
      # - text: "Subscribe"
      #   file: subscribe.qmd
  


  page-footer:
    left: |
      {{< fa regular copyright >}} Katherine Siegel, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [these folks.](/posts/quarto-website-migration.html)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/katherinesiegel/website)


format:
  html:
    theme: 
      - html/ath.scss
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
