project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!certificate*"
  output-dir: docs
  resources:
    - "files/"

execute:
  # Re-render only when source changes
  freeze: auto

description-meta: "Katherine Siegel"

website:
  title: "Katherine Siegel"
  # site-url: "https://github.com/katherinesiegel/website"
  # repo-url: https://github.com/katherinesiegel/website
  # description: "Katherine Siegel"
  # favicon: /files/icon.png 
  # twitter-card: 
  #   creator: "@kjohannetsiegel"
  # cookie-consent: true    
  search: true
  sidebar:
    background: "#5E3B49"
    pinned: true
    align: center 
    tools:
      - icon: github
        href: https://github.com/katherinesiegel/website
    style: docked
    contents:
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching & Mentoring
        href: teaching.qmd
  


  page-footer:
    left: |
      [{{< ai google-scholar >}}](https://scholar.google.com/citations?user=IhOqSsIAAAAJ)
      [{{< fa brands github >}}](https://github.com/katherinesiegel/)
      [{{< fa brands twitter >}}](https://mobile.twitter.com/kjohannetsiegel)

    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      
format:
  html:
    theme: sandstone
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
