---
title: "Publications"
---

## Peer-Reviewed
Please email me if you would like a pdf copy of a publication, or vist my [Google Scholar page](https://scholar.google.com/citations?user=IhOqSsIAAAAJ&hl=en&oi=ao). 

### Published   
**Siegel, K.J.**, Larsen, L., Stephens, C., Stewart, W., Butsic, V. 2022. Quantifying drivers of change in social-ecological systems: land management impacts wildfire probability in forests of the western US. _Regional Environmental Change_ **22**. [doi:10.1007/s10113-022-01950-y](https://doi.org/10.1007/s10113-022-01950-y).

**Siegel, K.J.**, Macaulay, L., Shapero, M., Becchetti, T., Larson, S., Mashiri, F., Waks, L., Butsic, V. 2022. Impacts of
livestock grazing on wildfire probability vary by region and vegetation type in California. _Journal of Environmental Management_ **322**, 116092. [doi:10.1016/j.jenvman.2022.116092](https://doi.org/10.1016/j.jenvman.2022.116092).

Kinnebrew, E., Ochoa, J., French, M., Mills-Novoa, M., Shoffner, E., **Siegel, K.J.** 2022. Biases and limitations of Global Forest Change and author-generated land cover maps in detecting deforestation in the Amazon. _PLoS ONE_ **17**(7), e0268970. [doi:10.1371/journal.pone.0268970](https://doi.org/10.1371/journal.pone.0268970).

Shapero, M., **Siegel, K.J.**, Gallo, J., Brice, J., Butsic, V. 2022. Land cover conversion and land use change combine to reduce grazing. _Journal of Land Use Science_ **17**, 339-350. [doi:10.1080/1747423X.2022.2086311](https://doi.org/10.1080/1747423X.2022.2086311).

**Siegel, K.J.**, Farah Perez, A., Kinnebrew, E., Mills-Novoa, M., Ochoa, J., Shoffner, E. 2022. Integration of qualitative and quantitative methods for land use change modeling in a protected area in an Amazonian deforestation frontier. _Conservation Biology_. [doi: 10.1111/cobi.13924](https://doi.org/10.1111/cobi.13924).

Free, C.M., Cabral, R.B., Froehlich, H.E., Battista, W., Ojea, E., O'Reilly, E., Palardy, J.E., Garcia Molinos, J., **Siegel, K.J.**, Arnason, R., Juinio-Meñez, M.A., Fabricius, K., Turley, C., Gaines, S.D. 2022. Expanding ocean food production under climate change. _Nature_ **605**(7910), 490-496. [doi: 10.1038/s41586-022-04674-5](https://doi.org/10.1038/s41586-022-04674-5).

Kinnebrew, E., Shoffner, E., Farah Perez, A., Mills-Novoa, M., Ochoa, J., **Siegel, K.J.** 2020. A review and typology of methodological approaches to interdisciplinary mixed methods research in land change science and environmental management. _Conservation Biology_ **35**, 130-141. [doi: 10.1111/cobi.13642](https://doi.org/10.1111/cobi.13642).

**Siegel, K.J.**, Cabral, R.B., McHenry, J., Ojea, E., Owashi, B., Lester, S.E. (2019) Sovereign states in the Caribbean have lower social-ecological vulnerability to coral bleaching than overseas territories. _Proceedings of the Royal Society B_ **286**(1897), 20182365. [doi: 10.1098/rspb.2018.2365](https://doi.org/10.1098/rspb.2018.2365).

McDonald, G., Campbell, S., Karr, K., Clemence, M., Granados-Dieseldorff, P., Jakub, R., Kartawijaya, T., Mueller, J.C., Prihatinningsing, P., **Siegel, K.J.**, Syaifudin, Y. (2018) An adaptive assessment and management toolkit for data-limited fisheries. _Ocean & Coastal Management_ **152**(1): 100-119. [pdf](https://www.researchgate.net/profile/Stuart_Campbell19/publication/321443262_An_adaptive_assessment_and_management_toolkit_for_data-limited_fisheries/links/5c0e3b4c92851c39ebe24fcd/An-adaptive-assessment-and-management-toolkit-for-data-limited-fisheries.pdf)

Leslie, H., Basurto, X., Nenadovic, M., Sievanen, L., Cavanaugh, K., Cota-Nieto, J., Erisman, B., Finkbeiner, E., Hinojosa-Arango, G., Moreno‐Báez, M., Nagavarapu, S., Reddy, S., Sanchez-Rodríguez, A., **Siegel, K.J.**, Ulibarria-Valenzuela, J.J., Hudson Weaver, A., Aburto-Oropeza, A. (2015) Operationalizing the social-ecological systems framework to assess sustainability. _Proceedings of the National Academy of Sciences_ **112**(19): 5979-5984. [doi: 10.1073/pnas.1414640112](https://doi.org/10.1073/pnas.1414640112).

#### In revision and in review
LoPresti, A., Hayden, M., **Siegel, K.J.**, Poulter, B., Dee, L. Remote sensing applications for prescribed burn
research. In review at _Journal of Applied Ecology_.

Rybski, D., Hemond, O., Wartenberg, A., **Siegel, K.J.**, Butsic, V. Assessing fire landscape connectivity in California using predictive percolation. In revision at _Environmental Research Letters_.


## Conference Proceedings

Thomas, L., **Siegel, K.**, Owashi, B., Estep, A., Gedamke, T., & Lester, S. 2015. [Determining effective fisheries monitoring and assessment approaches in data-limited contexts: a case study of the fisheries in Montserrat and Curacao.](http://proceedings.gcfi.org/proceedings/determining-effective-fisheries-monitoring-and-assessment-approaches-in-data-limited-contexts-a-case-study-of-the-fisheries-in-montserrat-and-curacao/?_sf_s=thomas&_sfm_volume=68) *Proceedings of the 68th Gulf and Caribbean Fisheries Institute Conference*, Panama City, Panama.


## Conference Presentations
**Siegel, K.J.**, Macaulay, L., Shapero, M., Becchetti, T., Larson, S., Mashiri, F., Waks, L., Butsic, V. Impacts of livestock grazing on wildfire probability vary by region and vegetation type in California. *Ecological Society of America & Canadian Society of Ecology and Evolution*, August 2022, Montreal, Canada.

**Siegel, K.J.** Collaborations with Cooperative Extension for use- and stakeholder-inspired wildfire science. *NOAA Climate & Global Change Summer	Institute*, July 2022, Steamboat Springs, Colorado.

**Siegel, K.J.** Impacts of land management and wildfire severity on post-fire forest composition and functioning in the western US. *NOAA Climate & Global Change Summer	Institute*, July 2022, Steamboat Springs, Colorado.

**Siegel, K.J.**, Larsen, L., Stephens, C., Stewart, B., Butsic, V. Quantifying drivers of change in social-ecological systems: land management impacts wildfire probability in forests of the western US. *Ecological Society of America Annual Meeting*, August 2021.

**Siegel, K.J.**, Mills-Novoa, M., Farah Perez, A., Kinnebrew, E., Ochoa, J., Shoffner, E. Synthesizing quantitative and qualitative understandings of deforestation drivers and solutions in protected areas in the Amazon. *American Association of Geographers Annual Meeting*, April 2020, Denver, CO.

**Siegel, K.**, Cabral, R., McHenry, J., Ojea, E., Owashi, B., & Lester, S. Marine resource management and social-ecological vulnerability to coral bleaching in the Caribbean. *Latin America & the Caribbean Congress for Conservation Biology*, 25-27 July 2018, St. Augustine, Trinidad & Tobago.  

**Siegel, K.**, Englander, G., Errickson, F., McDonald, G., Kleisner, K., Battista, W., Couture, J., Karr, K., Fujita, R. Projecting the ecological and economic impacts of fisheries reform in Myanmar. *International Marine Conservation Congress*, 24-29 June 2018, Kuching, Malaysia.  

**Siegel, K.** 'Think-and-do tanks': Building boundary organizations to connect the science and practice of marine conservation. *International Marine Conservation Congress*, 30 July-3 August 2016, St. John's, Newfoundland, Canada.

Clemence, M., Atrigenio, M., Carvalho, F., Cunningham, E., Fujita, R., Guirjen, J., Karr, K., **Siegel, K.** *et al.* Integrated decision support tools to inform small scale fisheries management. *ICES Annual Science Conference*, 21-25 September 2015, Copenhagen, Denmark.

McDonald, G., Campbell, S., Fox, H., Jakub, R., Karr, K., Kartawijaya, T., Mueller, J., **Siegel, K.**, & Thomas, L. An adaptive assessment and management toolkit for data-limited fisheries with a case study from Karimunjawa National Park, Indonesia. *International Congress for Conservation Biology*, 2-6 August  2015, Montpelier, France.

### Organized Symposia

Mills-Novoa, M., Kinnebrew, E., **Siegel, K.J.**, Shoffner, E., Ochoa, J. Synthesizing quantitative and qualitative understandings of deforestation drivers and solutions in protected areas in the Amazon. *American Association of Geographers Annual Meeting*, April 2021.

Mills-Novoa, M., **Siegel, K.J.**, Shoffner, E. Qualitative and quantitative approaches to understanding deforestation dynamics in the Amazon Basin. *American Association of Geographers Annual Meeting*, April 2020, Denver, CO.

**Siegel, K.**, & Clemence, M. Connecting theory and practice to advance marine conservation science and outcomes. *International Marine Conservation Congress*, 30 July-3 August 2016, St. John's, Newfoundland, Canada.


### Poster Presentations

Englander, A.G., Errickson, F., Norman, K., **Siegel, K.**, & Tribble, C. Data Science Collaborations with Conservation Nonprofits, Environment and Society DS421 NRT. *Berkeley Institute for Data Science, Data Science Faire*, 2018, Berkeley, California.  

**Siegel, K.**, Lasch, C., Reddy, S., & Leslie, H. Integrating ecological and institutional considerations into marine conservation planning in Mexico's Gulf of California. *International Marine Conservation Congress*, 14-18 August 2014, Glasgow, Scotland.
