---
title: "Teaching & Mentoring"
---

### Teaching Philosophy  
I prepare students and mentees for lifelong learning by teaching critical thinking and problem-solving skills. In addition to instructing students in course content, I empower them to develop skills to pursue self-directed learning beyond the classroom. I accomplish this by emphasizing active learning and demonstrating the applications of classroom concepts to contemporary issues.  

I strive to create an equitable and inclusive learning environment through guidelines for classroom interactions and integrating historically-excluded perspectives into class. During my PhD, I earned a Certificate in Teaching and Learning in Higher Education. This certification included classroom observation and feedback from a faculty mentor, syllabus design, and coursework in effective and inclusive pedagogy. I was nominated for the Extraordinary Teaching in Extraordinary Times Award in 2021 in recognition of my student-centered teaching during COVID-19 shutdowns.

### Courses Taught 
**University of Colorado-Boulder**  
*Causal Inference for Ecology & Evolutionary Biology*, Co-Instructor of Record (course website [here](https://katherinesiegel.github.io/EBIOcausalinference/))

**University of California-Berkeley**  
*Principles of Conservation Biology*, Graduate Student Instructor  
*Fire: Past, Present, and Future Interactions with the Peoples and Ecosystems of California*, Graduate Student Instructor

### Mentoring  
I view mentoring as an important vehicle for addressing obstacles to diversity, equity, inclusion, and justice in higher education, STEM, and the environmental community. I have mentored 14 undergraduate researchers at UC Berkeley and CU Boulder, and for the past three years, I have mentored a first-generation college student through [Oakland Promise](https://oaklandpromise.org/). I have also supported prospective grad students through the grad school application process through [Cientifico Latino](https://www.cientificolatino.com/).